name: Cronjob update

on:
  schedule:
    # run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  cronjob_update:
    name: Cronjob update

    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run update
        run: ./run.sh
